### ISSUE TITLE
sys:check -> Call to a member function fetchOne() on a non-object 

### ISSUE THREAD

**Issue by it-scripter** [netz98/n98-magerun#672] opened 2015-09-02 12:39 UTC
Hello!

On a server just before installing Magento I'm trying to check the requirements by using sys:check and the result is this message: 

PHP Fatal error:  Call to a member function fetchOne() on a non-object in phar:///var/www/n98-magerun.phar/src/N98/Magento/Command/System/Check/MySQL/VersionCheck.php on line 22

In the folder /var/www are the files of magento 1.9.2

PHP: Version 5.5.9-1ubuntu4.11
n98-magerun version 1.97.5 

Best regards from Berlin and thanks a lot for n98-magerun,
Thorsten

**Comment by tkn98** [comment] 2015-09-02 13:58
@it-scripter: Thanks for reporting the issue, there ineed is a problem calling that check *prior* installation as it requires the database connection which most likely in your scenario is not yet configured.

An upcomming fix will prevent the fatal error at that stage and report an error that the database connection could not be retrieved from the resource model, so the mysql version remains unchecked in your scenario.

**Comment by tkn98** [comment] 2015-09-02 14:03
@it-scripter: I wonder a bit,, for your scenario, don't you see a

  [Zend_Exception]                                                   
  dbModel read resource does not implement Zend_Db_Adapter_Abstract

first with sys:check? Which Magento version are you using?

**Comment by it-scripter** [comment] 2015-09-02 14:33
Thanks for your fast response. 
And: no, there is only this single line of message - never looked into the logs.

The magento version I'm going to install ist 1.9.2.1

Now I have edit the config.xml by hand to set the db connection and now the sys:check was successful - of course with the limitations of an unset system. 

Just a hint: I'm missing in the result a line about ionCube - this is optional but mostly essential. 

Greetings

**Comment by ktomk** [comment] 2015-09-02 16:59
@it-scripter: What kind of output do you miss about ionCube? A hint that you should remove it from the system? :)

**Comment by ktomk** [comment] 2015-09-02 17:02
@it-scripter: I just updated the unstable version. Can you give it a try w/o the config.xml and check if the issue is fixed and no additional fatal error is triggered?

**Comment by it-scripter** [comment] 2015-09-09 08:10
@ktomk I'm sorry about my late answers. Here there are:
About ionCube: There are some magento extensions they need ionCube and so it would be helpful to see that ionCube is running (with the right version)

My test results with the unstable version of 98-magerun are: 
Without the local.xml the check is finished completely, with a hint about the missed file. 
With the local.xml the check finished with everything is okay

**Comment by tkn98** [comment] 2015-09-09 09:57
Thanks for your feedback. I think we can close your issue here now, it will be part of the next stable release.

About ioncube it's the first time I can remember it's brought up. If you like you can open an issue about it alone. Sounds to me you want to be able to see whether or not that module is enabled and which version it has (informational). Is that correct?

**Closed by tkn98** 2015-09-09 09:57 UTC

**Comment by it-scripter** [comment] 2015-09-09 11:18
@tkn98 about iconCube: You are right. 
Thanks for your quick bug-fix.
