### ISSUE TITLE
Remove usage of non-existent DialogHelper

### ISSUE THREAD

**Issue by jameshalsall** [netz98/n98-magerun#563] opened 2015-05-21 08:45 UTC
I'm seeing these warnings when running magerun:

`Warning: include(): Failed opening 'Composer\Command\Helper\DialogHelper.php' for inclusion`

which was removed in the alpha10 release in this PR: https://github.com/composer/composer/pull/3983

**Comment by tkn98** [comment] 2015-05-21 10:08
Thanks  for the report. Perhaps a problem as composer version is hard to pin.

**Comment by jameshalsall** [comment] 2015-05-23 20:55
It should be fine if you depend on the alpha..

`"composer/composer": "~1.0.0@alpha"`

**Comment by tkn98** [comment] 2015-05-26 07:18
But that won't solve the flaw you report. In any case this might be better than

    "composer/composer": "1.0.*@dev",

as we have it currently. I'll file the requirement.

Old API:

	/** @var \Symfony\Component\Console\Helper\DialogHelper $dialog */
	$dialog = $this->helperSet->get('dialog');
	return $dialog->ask($output, $question, $default);

New API:

	/** @var \Symfony\Component\Console\Helper\QuestionHelper $helper */
	$helper = $this->helperSet->get('question');
	$question = new Question($question, $default);
	return $helper->ask($this->input, $output, $question);
	
As this change introduces code on a level Magerun yet does not use, I suggest to wrap the new API so that its compatible to the old one.

**Comment by tkn98** [comment] 2015-05-26 07:31
@jameshalsall: With which action did you get the error message. I ask because I'd like to reproduce it. Also do you remember the version of composer you had earlier w/o the problem? I think it might be an option to pin that version until the wrapper is in action.

**Comment by jameshalsall** [comment] 2015-05-26 08:05
I've never used this tool before last week, but I think if you lock composer to `1.0.0-alpha9` you will be fine.

**Comment by tkn98** [comment] 2015-05-26 09:23
@jameshalsall I still have problems to reproduce this issue. Can you share how you triggered the warning?

**Comment by jameshalsall** [comment] 2015-05-26 09:52
1. Added `"n98/magerun": "~1.96"` to composer.json
2. `composer update n98/magerun`
3. Run the n98-magerun binary (any command)

I see those warnings above all other output from the command.

Composer version is `1.0.0-alpha10`

**Comment by ozzyogkush** [comment] 2015-06-01 21:18
Simply cloning this repository and running `composer install` brings this issue up when trying to run commands. We've found that downgrading symfony/console from 2.6.* to 2.3.* seems to remove this issue when running the /bin/n98-magerun file.

    $ n98-magerun customer:delete 900
    PHP Fatal error:  Call to undefined method Symfony\Component\Console\Helper\DialogHelper::getQuestion() in phar:///n98-magerun/n98-magerun.phar/src/N98/Magento/Command/Customer/DeleteCommand.php on line 187

**Comment by ktomk** [comment] 2015-06-02 06:34
@ozzyogkush  Thank you for the feedback. So is it that you checked out the master or develop branch after you cloned?

**Comment by ozzyogkush** [comment] 2015-06-02 13:55
@ktomk we're using chef's `git` resource to pull down revision `1.96.1` and running composer off of that.

**Comment by ozzyogkush** [comment] 2015-06-02 16:04
I will note that everything seems to work fine without modifying `composer.json` if I pull down `1.95.0`. I noticed that in the latest `composer.lock` file you have `composer/composer` now requiring `symfony/console": "~2.5` instead of `~2.3`.

**Comment by ktomk** [comment] 2016-02-01 18:34
@ ozzyogkush: Sorry for the late feedback. Is this still an issue for you? I've checked and we merged in fixes in #651 back in Sep 2015. Also just let me know if you didn't check any longer just so that I know.

**Comment by ozzyogkush** [comment] 2016-02-04 23:13
Have not messed with the latest version of this, we're running off of a branch of 1.95.0

**Comment by ktomk** [comment] 2016-02-05 17:55
@ozzyogkush: I would then close this issue for now as I believe this problem is fixed in the current version. If I'm wrong, we can re-open this again.

**Closed by ktomk** 2016-02-05 17:55 UTC
Labels: bug, question
