### ISSUE TITLE
[install] dbHost not respected

### ISSUE THREAD

**Issue by arosenhagen** [netz98/n98-magerun#462] opened 2015-01-12 12:57 UTC
the install command currently doesn't respect the dbHost parameter correctly. may be related to #436

**Comment by cmuench** [comment] 2015-01-18 08:29
I will check this today.

**Comment by cmuench** [comment] 2015-01-18 14:39
Confirmed. The problem is that if not all minimal parameters (dbHost, dbUser, dbPass, dbName) are passed we ask for every parameter again. That's ok to ask again, because if any parameter was wrong the user can correct it. The wrong thing is that the default value in interactive mode should use the given parameters as default. I will change the behavior.

**Comment by cmuench** [comment] 2015-01-20 07:53
Should be fixed. Can you check it again?

**Closed** 2015-03-09 07:56 UTC
Labels: bug
