### ISSUE TITLE
PHP 7.4/8 support (OpenMage 20.x)

### ISSUE THREAD

**Issue by Schrank** [netz98/n98-magerun#1133] opened 2020-12-02 11:53 UTC
## Feature description

I read https://github.com/netz98/n98-magerun/issues/1014 and in the end it was fixed. Are you interested in a PHP 7.4/8 PR?

## Problem and motivation
MageOne is offering Magento Support for 7.3 and 7.4 is on the roadmap and other vendors do that as well. n98-magerun is a brilliant tool to assist us in all kinds of stuff, so maintaining it, so we don't get spammed with error messages is helpful for us.

## Is this something you're interested in working on
Yes

**Comment by ktomk** [comment] 2020-12-02 15:24
I could offer technical assistance / support if wanted. E.g. covering this in the build, what do you think @cmuench ?

**Comment by cmuench** [comment] 2020-12-02 15:54
@ktomk yes, of course. To be hones, I have currently no real Magento 1 project anymore. So I need help to be up-to-date.

**Comment by cmuench** [comment] 2020-12-02 16:10
@ktomk btw... the build is currently broken. I tink it's the Composer 2 update in the Travis images. For the n98-magerun2 project, I ported everything to Github Actions.

**Comment by Schrank** [comment] 2020-12-02 16:12
If someone is porting things to GA, we™ might want to add GPG signatures and phar files directly, so we can add it easily to five 🙈

**Comment by ktomk** [comment] 2020-12-02 20:04
Okay, I'll take a look into the GH actions build then. This should cover our backs @cmuench  (btw. missed the UG date, hopefully next time)

@Schrank: One thing after the other, this would require to get the build reproducible which I deem feasible, but I want to look into getting it green first. You're asking this because of phive I assume, right?

**Comment by cmuench** [comment] 2020-12-02 20:08
We have already phive support.

**Comment by ktomk** [comment] 2020-12-02 21:04
And IIRC also checksums for brew, right? @cmuench

**Comment by cmuench** [comment] 2020-12-02 21:31
@ktomk the brew package is not maintained by me, but I think so.

**Comment by cmuench** [comment] 2020-12-04 09:15
@ktomk the travis job is running again. Did a quick fix and downgraded Composer to v1.
For the future I see that we also migrate this project to Github Actions.

**Comment by ktomk** [comment] 2020-12-23 00:29
I've just filed (and merged) PR #1147 which adds an extra use test (the install command) into Magerun Github CI.

It is a nice by-catch for mandatory PHP 8.0 compatibility with the Openmage 20.0.4 version (from now on builds will break if magerun can't install with PHP 8.0).

It already shows part of current level of PHP 8.0 compatibility: `composer install`  requires `--ignore-platform-reqs` and the Magento fork needs to be Openmage (Adobe Magento baseline no compatibility with PHP 8 - likely is expected).

Take it with a grain of salt thought, this is not running any other kind of tests under PHP 8.0 (yet).

I'll chew on the PHP version requirements from here a bit and extend the CI build appropriately.

**Comment by ktomk** [comment] 2021-02-22 07:44
PHP 8 compat for symfony-autocomplete dependency in #1167

**Comment by perryholden** [comment] 2022-03-04 16:42
It's been a while since the last post here. I am curious how PHP 8.X support is coming along, especially as the latest versions of OpenMage support PHP 8.

**Comment by cmuench** [comment] 2022-03-04 17:50
I am currently not working on that. My focus is currently n98-magerun2 with PHP 8.1 support.

**Comment by cmuench** [comment] 2022-07-15 13:44
I did some first work to support OpenMage 20.0.4.
https://github.com/cmuench/n98-magerun/tree/feature/php81

It's not easy because we have to update or rewrite at least this:

- CI Setup (configuration)
- Unit Tests
- All Symfony dependencies
- Try to be backwards compatible as possible

The branch contains a ddev setup with a command to install OpenMage in the container.
A lot of commands are working out of the box with PHP 8.1 and OpenMage. A lot are broken due to incompatible Symfony console etc.

![image](https://user-images.githubusercontent.com/211294/179235894-e6adde11-af73-4873-8f61-60553d4aa244.png)

**Comment by sreichel** [comment] 2022-11-22 22:56
I started to work on this and made some updates. (https://github.com/cmuench/n98-magerun/pull/83)

**Comment by cmuench** [comment] 2022-11-23 08:17
@sreichel wow. Thanks. Sadly I am currently injured and cannot really work on the PC.
I did a short review.

**Comment by ktomk** [comment] 2022-12-22 20:00
Just an update as I did some chore and finally closed #1138 by #1273 , within the workflow we now have:

- Test OpenMage on Ubuntu 20.04 with PHP 7.4 (green)
- Test OpenMage on Ubuntu 20.04 with PHP 8.0 (allow-failures, experimental)

Was a bit hasty today and thought I could get rid of Ubuntu 18.04 entirely in the workflows (gives deprecation warnings), but that turned out wrong. So these two are at least what could survive.

**Comment by sreichel** [comment] 2023-05-16 18:23
Think most of the work is done. (https://github.com/cmuench/n98-magerun/pull/87)

> It's not easy because we have to update or rewrite at least this:

- [ ] CI Setup (configuration)
- [ ] Unit Tests
- [x] All Symfony dependencies
- [x] Try to be backwards compatible as possible .... _"Choice questions" have changed, progessbars work different ... it will break some pluigns for sure_ :/

**Comment by cmuench** [comment] 2023-05-16 18:38
@sreichel wow. ♥️
I will try to review it soon.

**Comment by cmuench** [comment] 2023-05-17 13:38
@sreichel Seems that we have to update the Github Actions in the CI/CD. The system is not compatible anymore. We use a outdated Ubuntu.

**Closed** 2023-08-28 20:24 UTC
Labels: in progress

**Comment by sreichel** [comment] 2023-08-29 13:31
@cmuench i've some time to work on it. Seems something is broken. I cloned the project, started DDEV and used install command. 

- sample data is installed, even with default "no" selection
- base url is not set in core_config_data
- magento root folder is not detected, so no command works

Can you reproduce this?

**Comment by cmuench** [comment] 2023-08-29 13:48
@sreichel I can confirm that there are issues with the sample data.
I cannot confirm the installation issues. I was able to install OpenMage 20.0.20 from inside my ddev environment by using a fresh n98-magerun2.phar file (created with ./build.sh in the container).
Base-URL was also set.

**Comment by cmuench** [comment] 2023-08-29 13:50
@sreichel The installation via `ddev install-openmage 20.0.20` should also work.

**Comment by sreichel** [comment] 2023-08-29 15:46
@cmuench can you pls share the commands you've used?

```ddev . bin/n98-magerun some:command``` did not work for me.

I'll test ddev install-command later. Thanks.

Btw ... whats your setting for ```N98_MAGERUN_TEST_MAGENTO_ROOT```?

**Comment by cmuench** [comment] 2023-08-29 15:56
> Btw ... whats your setting for `N98_MAGERUN_TEST_MAGENTO_ROOT`?

`export N98_MAGERUN_TEST_MAGENTO_ROOT=/opt/magento-test-environments/magento_20_0_20/`

**Comment by sreichel** [comment] 2023-08-29 16:01
@cmuench thanks. Can it be added to `.ddev/config.yml`? And - how about to set a default DB-port? I work with phpStorms DB-tool a dont want to change the port every time.

**Comment by cmuench** [comment] 2023-08-29 16:35
@sreichel Yes, if we automatically would install a standardized OpenMage instance after `ddev start`.

**Comment by cmuench** [comment] 2023-08-29 16:36
@sreichel Let's do all the discussions here: #1275
