### ISSUE TITLE
Cache flush does not work properly (setup scripts not executed when accessing via browser)

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#613] opened 2015-07-21 09:55 UTC
When I use cache:flush and open magento in the webbrowser, my (new) setup scripts are not executed.
If I do `rm -rf var/cache/*` it works.

I use the file cache storage and 

```
    <cache>
         <backend>File</backend>
         <backend_options>
                 <hashed_directory_perm><![CDATA[777]]></hashed_directory_perm>
                 <cache_file_perm><![CDATA[666]]></cache_file_perm>
                 <cache_file_umask><![CDATA[666]]></cache_file_umask>
         </backend_options>
     </cache>
```

`cache:flush` also does a `reinitCache()` - do we really need this?

The situation after `cache:flush`:

```
alex@me:~/local-workspace/shop/public/var/cache$ ls -alh
total 40K
drwxrwxrwx 10 www-data www-data 4,0K Jul 21 11:54 .
drwxrwxr-x 16 alex      www-data 4,0K Jul  9 11:41 ..
drwxrwxrwx  2 alex      alex      4,0K Jul 21 11:54 mage--2
drwxrwxrwx  2 alex      alex      4,0K Jul 21 11:54 mage--4
drwxrwxrwx  2 alex      alex      4,0K Jul 21 11:54 mage--5
drwxrwxrwx  2 alex      alex      4,0K Jul 21 11:54 mage--6
drwxrwxrwx  2 alex      alex      4,0K Jul 21 11:54 mage--7
drwxrwxrwx  2 alex      alex      4,0K Jul 21 11:54 mage--8
drwxrwxrwx  2 alex      alex      4,0K Jul 21 11:54 mage--9
drwxrwxrwx  2 alex      alex      4,0K Jul 21 11:54 mage--b
```

**Comment by tkn98** [comment] 2015-07-21 11:24
The *cache:flush* command should empty the cache. So next to the problem that this does not happen is that the command itself does not realize that the operation went wrong. Have you checked the return code?

Also what I see is that the group ownership is not *www-data*. Could this be related?

**Comment by amenk** [comment] 2015-07-21 11:26
Yes it is not www-data because I run it as "alex". When I remove the line 

https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Cache/FlushCommand.php#L42

everything is fine.

I do not understand why the cache is reinitialized. I somehow expect the cache to be completely empty after running that commnad.

**Comment by amenk** [comment] 2015-07-21 11:49
I think I found the problem. Have a look at

https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Core/Model/App.php#L424

In this part the update scripts are normally run if `loadlModulesCache()` is false.
But when opening the shop after `n98-magerun.phar ca:flush`, this is true and so the whole part is skipped.

Basically https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Cache/AbstractCacheCommand.php#L41 does the same like Magento's `initModules()` but without running the update scripts.

So update scripts are never run in such cases. Looks like it does not have anything to do with access rights. Just a logical problem.

**Comment by tkn98** [comment] 2015-07-21 13:10
Perhaps first run update scripts via `sys:setup:run` and then flush the cache?

**Comment by amenk** [comment] 2015-07-21 13:30
I know that it is possible to run the scripts like this. But it should also work by flushing the cache. 
That was working before but broke in March https://github.com/netz98/n98-magerun/commit/1c7e64e8d7b4b434266bf6970cc0435c18e590af

**Comment by amenk** [comment] 2015-07-28 16:48
ping @cmuench

**Comment by cmuench** [comment] 2015-07-28 19:28
@amenk We added that to prevent a race condition after a cache clear. See ticket #483.
Is `sys:setup:run` working after `cache:flush` ?

**Comment by amenk** [comment] 2015-07-29 07:25
yes, `sys:setup:run` is working.
I saw that ticket/commit with the race condition, even I did not fully understand it.
But I think we have to find a different solution there. From my point of view it is a regression. In earlier magerun versions, the cache was left empty after a `cache:flush`. I think a user would not expect to the cache to be initialized after a `cache:flush`.

It can easily happen that the setup scripts do not run, causing nasty bugs. I thought about adding `sys:setup:run` into the `cache:flush`, but that also seems not what the users expects.

**Comment by amenk** [comment] 2015-08-04 13:00
So what can we do? I think this is a pretty critical problem as it always causes invalid states after cache flushes.

**Comment by tkn98** [comment] 2015-08-04 13:05
@amenk: Can you review the issue I cross-linked (#583) ? I feel we have some more information in there.

**Comment by hostep** [comment] 2015-08-10 12:52
Sorry to hijack this thread, but the issue seems to be related to yet another issue we have with trying to flush the cache using magerun.

For a certain project, we use the https://github.com/GordonLesti/Lesti_Fpc module and when we want to flush the (fpc) cache, it doesn't clear the fpc cache, not with `cache:flush` or `cache:clean` or `cache:clean fpc`, the only thing which seems to work is going into the backend, select all the caches and execute the 'Refresh' action.
Maybe it will also work if we remove the files in `var/cache`, but I haven't had a chance to test that yet.

So I mean to say that there definitely seems to be something wrong with flushing the cache.

(We also noticed the original problem @amenk mentions btw, where the setup scripts don't run, which can be really annoying sometimes :))

**Comment by tkn98** [comment] 2015-08-11 12:47
@hostep: Can you confirm it did work earlier with Magerun? And do you have access to the development version (just asking first as we might have something to beta-test soon, not yet)?

**Comment by amenk** [comment] 2015-08-11 13:00
I am sure it worked earlier.

**Comment by ktomk** [comment] 2015-08-11 16:40
I've now been running tests with the changes from #483 but it looks like that still - even removed - after the setup of any 1.9.x caches can't be enabled (on travis).

**Comment by hostep** [comment] 2015-08-11 18:15
@tkn98: I can't remember if it used to work with Magerun versions prior to 1.95 (the setup scripts I mean, we've only been using the fpc module since a couple of months, so we never used it with a version prior to 1.95).
If I have some time and you have a dev/beta version for me to test with, I can give it a shot.

(btw: I don't think the `cache:dir:flush` command which just got added is a good addition, since some people use Redis or Memcached or something like that for their cache storage, I think its better with the `cache:flush` and/or `cache:clean` commands, which are a nice abstraction around the actual cache storage engine which is being used, just my 2 cents :))

**Comment by tkn98** [comment] 2015-08-12 09:35
@hostep: Thanks for the feedback, no you don't need to yet make tests about that, I was just asking for feedback. Thanks!

----

I have run some tests on my end while debugging this. It's not done with reverting the changes in the other ticket. This is an issue with the `install` command in Magerun for all Magento 1.9.x versions.

I suspect it's with the initialization sequence of the caches in Magento now. So far I could re-elevate by applying the command twice (new process needed). So it's hard to debug as it requires to re-install all the time.

**Comment by amenk** [comment] 2015-08-26 11:29
What is the status of the original issue after @hostep's hijacking? I think it is quite important. I end up typing `rm -rf var/cache/*` alot these days. Like in times before magerun :-(

**Comment by hostep** [comment] 2015-08-26 13:30
In version 1.97.5 there is now a `cache:dir:flush` command which should do this exact thing. I haven't had the time to test it out yet. (although I believe this isn't the correct fix :))

**Comment by amenk** [comment] 2015-08-26 14:07
Sure but it is also just a workaround, as I believe that the bug also would appear on Redis. And I don't want to change my shortcut button in PHPStorm :)

**Comment by tkn98** [comment] 2015-08-27 10:17
`cache:dir:flush` does only flush the cache directory (for the default cache), for example it does not flush Full-Page-Cache on Enterprise (which it probbably could similarly) nor does it handle other backends like said Redis. So it's not a workaround, just an additional tool in the box. Maybe not the sharpest one :)

**Comment by ktomk** [comment] 2015-08-27 18:05
@amenk 

> I do not understand why the cache is reinitialized. I somehow expect the cache to be completely empty after running that command.

When I remember the tracks of this report here right and what I've seen in the code while looking into it, this is because Magento underwent some changes on initialization, cache and config. If you can (sorry if that would be again) suggest some other code that works without and makes the command more robust and stable that would be great. IIRC you also had the idea of some command-line switch which I think is great to offer different methods so to get the best out of it. All what I've seen so far ist that the whole cache initialization and re-initialization with new config somehow follows an intertwined path through quite some files.

Also please see the note https://github.com/netz98/n98-magerun/issues/613#issuecomment-130236753

**Comment by amenk** [comment] 2015-08-28 07:05
Did anybody trace down what Magento is doing when flushing the cache via backend?

I mean another option would be do add running of the update scripts in the cache:flush like it is done in the Magento core. So it would be more consistent.

Also I think that the `cache:dir:flush` would cause the same problem like we have here?

My understanding is/was that @cmuench fix was only for that edge case (#483) when you change the db server IP? Actually I did not yet fully understand what is going on in #483 ...

**Comment by tkn98** [comment] 2015-08-28 07:57
For a test I already reverted these changes and it didn't helped with the issue here. So this is not a regression but just changes within Magento we need to deal with. Version of change was 1.9.x something from top of my head.

**Comment by amenk** [comment] 2015-08-28 08:02
Okay, I just tested with an older EE (1.13)

**Comment by ktomk** [comment] 2015-08-28 19:00
I think it's never wrong to ask when you can write a good question :) I haven't yet fully understood the problem so would have problems to write a good question.

**Comment by tkn98** [comment] 2016-12-15 12:49
For the file-based cache there is the `cache:dir:flush` command (since 02e7c692d960e98d7778918e339cde977ca8f5b6) which will report errors when can't empty a path within the (file) cache.

I close this issue for now as there is little traction the last months. In case `cache:dir:flush` is not for the rescue (or inappropriate) we can re-open it in case of a concrete issue.

**Closed by tkn98** 2016-12-15 12:49 UTC
Labels: bug
