### ISSUE TITLE
sys:setup:run exists with code 0 on error

### ISSUE THREAD

**Issue by barbazul** [netz98/n98-magerun#854] opened 2016-08-20 18:29 UTC
This was suposedly fixed a long time ago but I just run into it today.

Check #571 and #384 

I am running n98-magerun version 1.97.22

**Comment by ktomk** [comment] 2016-08-22 06:14
Well, where exactly did it fail for you?

And yes you're right, it should have an non-zero status on error.

**Comment by ktomk** [comment] 2016-08-25 05:02
I'm unable to reproduce your problem. Please verify the version you're using and provide it.

Also provide more information into which kind of error you run.

Until then I'll close the issue.

**Comment by tkn98** [comment] 2016-08-25 09:56
Let it stay open until clarified.

**Comment by barbazul** [comment] 2016-08-25 10:37
I'll try to build an example later, but it's a simple case.

A setup script throws an exception (like a duplicate table or a FK constraint failing).
Setup exits and dumps both the error and the content of the offending script.
Exit code is 0.

I am running n98-magerun version 1.97.22 (already mentioned this in the original post)

**Comment by tkn98** [comment] 2016-08-25 11:02
Hmm, that case is covered over here. No idea why this doesn't work on your end, so an example is very welcome.

**Comment by tkn98** [comment] 2016-09-12 11:14
No feedback over more than two weeks, closing.

**Comment by barbazul** [comment] 2016-10-16 16:14
Sorry it took me a while to get back to this. 

I created this repo with a a very simple example of the error.

https://github.com/barbazul/magerun-setup-example

**Comment by ktomk** [comment] 2016-10-16 21:37
@barbazul: Thanks for creating the example, with some little modification of the instructions I was now able to reproduce the issue. The exit status is wrongfully 0.

**Comment by ktomk** [comment] 2016-12-17 00:30
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.

**Closed by ktomk** 2016-12-17 00:30 UTC
Labels: bug, in progress
