### ISSUE TITLE
Cache Clean or Cache Flush not working properly with Redis

### ISSUE THREAD

**Issue by andreasemer** [netz98/n98-magerun#775] opened 2016-02-16 12:01 UTC
It seems to be impossible to clean oder flush the cache with Magerun, if Redis is used as a backend cache. 

I have tested this with: 
Magento 1.9.2.1
Magento 1.9.2.3
Redis 3.0.6
Magerun 1.97.11
Magerun 1.97.5
PHP 5.6.15
PHP 5.6.17

If the cache is in files, the clean and flush command works as expected. Its also possible to clear of flush the cache in the Magento Backend. 

This is the Redis part of a sample local.xml, which is used:

```
<session_save>db</session_save>
        <redis_session>                       <!-- All options seen here are the defaults -->
            <host>127.0.0.1</host>            <!-- Specify an absolute path if using a unix socket -->
            <port>6383</port>
            <password></password>             <!-- Specify if your Redis server requires authentication -->
            <timeout>2.5</timeout>            <!-- This is the Redis connection timeout, not the locking timeout -->
            <persistent></persistent>         <!-- Specify unique string to enable persistent connections. E.g.: sess-db0; bugs with phpredis and php-fpm are known: https://github.com/nicolasff/phpredis/issues/70 -->
            <db>0</db>                        <!-- Redis database number; protection from accidental loss is improved by using a unique DB number for sessions -->
            <compression_threshold>1</compression_threshold>  <!-- Set to 0 to disable compression (recommended when suhosin.session.encrypt=on); known bug with strings over 64k: https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/issues/18 -->
            <compression_lib>gzip</compression_lib>              <!-- gzip, lzf, lz4 or snappy -->
            <log_level>1</log_level>               <!-- 0 (emergency: system is unusable), 4 (warning; additional information, recommended), 5 (notice: normal but significant condition), 6 (info: informational messages), 7 (debug: the most information for development/testing) -->
            <max_concurrency>10</max_concurrency>                 <!-- maximum number of processes that can wait for a lock on one session; for large production clusters, set this to at least 10% of the number of PHP processes -->
            <break_after_frontend>5</break_after_frontend>       <!-- seconds to wait for a session lock in the frontend; not as critical as admin -->
            <break_after_adminhtml>30</break_after_adminhtml>
            <first_lifetime>600</first_lifetime>                 <!-- Lifetime of session for non-bots on the first write. 0 to disable -->
            <bot_first_lifetime>60</bot_first_lifetime>          <!-- Lifetime of session for bots on the first write. 0 to disable -->
            <bot_lifetime>7200</bot_lifetime>                    <!-- Lifetime of session for bots on subsequent writes. 0 to disable -->
            <disable_locking>0</disable_locking>                 <!-- Disable session locking entirely. -->
            <min_lifetime>60</min_lifetime>                      <!-- Set the minimum session lifetime -->
            <max_lifetime>2592000</max_lifetime>                 <!-- Set the maximum session lifetime -->
        </redis_session>

        <cache>
            <backend>Cm_Cache_Backend_Redis</backend>
            <backend_options>
                <server>127.0.0.1</server> 
                <port>6382</port>
                <persistent></persistent> <!-- Specify unique string to enable persistent connections. E.g.: sess-db0; bugs with phpredis and php-fpm are known: https://github.com/nicolasff/phpredis/issues/70 -->
                <database>0</database> <!-- Redis database number; protection against accidental data loss is improved by not sharing databases -->
                <password></password> <!-- Specify if your Redis server requires authentication -->
                <force_standalone>0</force_standalone>  <!-- 0 for phpredis, 1 for standalone PHP -->
                <connect_retries>1</connect_retries>    <!-- Reduces errors due to random connection failures; a value of 1 will not retry after the first failure -->
                <read_timeout>10</read_timeout>         <!-- Set read timeout duration; phpredis does not currently support setting read timeouts -->
                <automatic_cleaning_factor>0</automatic_cleaning_factor> <!-- Disabled by default -->
                <compress_data>1</compress_data>  <!-- 0-9 for compression level, recommended: 0 or 1 -->
                <compress_tags>1</compress_tags>  <!-- 0-9 for compression level, recommended: 0 or 1 -->
                <compress_threshold>20480</compress_threshold>  <!-- Strings below this size will not be compressed -->
                <use_lua>0</use_lua> <!-- Set to 1 if Lua scripts should be used for some operations -->
            </backend_options>
        </cache>

        <fpc>
            <lifetime>86400</lifetime>
            <backend>Cm_Cache_Backend_Redis</backend>
            <backend_options>
                <server>127.0.0.1</server>
                <port>6384</port>
                <persistent>cache-fpc</persistent>
                <database>1</database>
                <password></password>
                <force_standalone>1</force_standalone>
                <connect_retries>1</connect_retries>
                <lifetimelimit>86400</lifetimelimit>
                <read_timeout>10</read_timeout>
                <compress_data>1</compress_data>
                <compress_tags>1</compress_tags>
                <compress_data>gzip</compress_data>
            </backend_options>
        </fpc>
```

Can anyone reproduce this?

**Comment by ktomk** [comment] 2016-02-16 19:00
I wonder what triggers this. Can you share how you verify that it's not cleared? Just some points how this can be reproduced.

**Comment by robbieaverill** [comment] 2016-02-17 22:33
Related: #754

**Comment by pschoenmakers** [comment] 2016-02-23 12:55
Reproduced this:

98-magerun.phar cache:flush doesn't clear the redis cache for me.

n98-magerun 1.97.11
Magento 1.9.0.1
Redis 3.0.7
PHP 5.6.18

Workaround for now is manually doing a redis-cli flushall

**Comment by mklooss** [comment] 2016-02-23 20:26
redis-cl -n #number# flushdb

is a better choice, when ur also use redis for sessions

**Comment by ktomk** [comment] 2016-02-23 22:14
I do understand that the redis cache is not cleared. What I'd like to understand is whether or not magerun reports that the cache is cleared (or not).So for those users who can reproduce this problem it would be interesting for me to learn about the exact command-line and the output. If you see confidential material in that output, please XXX it out if applicable.

I try to find out what the cause of this issue is and for that I need to pin-point it down as I can not reproduce it.

Technical background:

Magerun flushes the cache by triggering the Magento API on that. Example:

    Mage::app()->getCacheInstance()->flush();

The call to `getCacheInstance()` is a M1-common self-initializing static lazy-loader based on "global" configuration:

    $this->_config->getNode('global/cache');

If for *any* reason that configuration does not return the redis config, `flush()` will flush a non or different configured cache. So my assumption is that something along the configuration is out of line. I know that this has been reported earlier, so this is something known to happen and I can imagine that in such a situation `cache:flush` is likely wanted to be called.

So for everyone who can reproduce and wants to report: Can you post the call + output for your report? And can you try two times? (might sound silly, be there is a re-init-cache call in the command so this can make a difference).

**Comment by pschoenmakers** [comment] 2016-02-23 22:33
![cache](https://cloud.githubusercontent.com/assets/15877946/13268888/3e670374-da85-11e5-8563-dad0369ed694.png)

I know that my Redis cache hasn't cleared as the Lesti FPC I use still have pages in it's cache. When looking at the response headers I still see that those pages are coming from the cache. After clearing the full Redis cache with redis-cli those pages aren't coming from the cache are show an age of 0. 

If there is anything else I can provide / test let me know.

**Comment by ktomk** [comment] 2016-02-24 07:22
@pschoenmakers: Thanks for more of these infos, I think there is also a cache stats command, could you fill the cache, clear it and check before and after with that cache stats command what the cache itself reports? I just ask because flushing via redis will for sure clear the whole cache as the whole storage has been flushed (we might add a command for that, too, but I'd like to first understand what the exact cause is here).

**Comment by pschoenmakers** [comment] 2016-02-24 08:18
**Before cache:flush**
```
+-------------------------------------------------------+---------------------+
| LAYOUT_1DB19537F0609226170427EC93F12280A              | 1970-01-01 00:00:00 |
| LAYOUT_4DCECCAF1B6A7E994C47B5B8D2F970C86              | 1970-01-01 00:00:00 |
| LAYOUT_4F16578BEE0E185E761811A3F67070EA6              | 1970-01-01 00:00:00 |
| LAYOUT_4A395F5D6F766A407D008AEAD2A7738BB              | 1970-01-01 00:00:00 |
| LAYOUT_47FCAD5FF3345A0EEB2BA38805512FF0F              | 1970-01-01 00:00:00 |
| LAYOUT_1994704772889409A9EEFDE3FE4DB5674              | 1970-01-01 00:00:00 |
| LAYOUT_40241515402BBECF7B99362F9F51EA4E6              | 1970-01-01 00:00:00 |
| LAYOUT_1984AA60FF5DECAB9BE8FE873FC005AE1              | 1970-01-01 00:00:00 |
| LAYOUT_41F7424E37F34ED44B0A90CDAB479845E              | 1970-01-01 00:00:00 |
| LAYOUT_4BFCBBDEDD299DD82E0FA5F2874093421              | 1970-01-01 00:00:00 |
| LAYOUT_4502952D49AD8923543093A8AEF42AE7B              | 1970-01-01 00:00:00 |
| LAYOUT_4E95AEC1094D56CE6CFD7791B97E3FCC8              | 1970-01-01 00:00:00 |
| LAYOUT_1BAE435C1C2CFBBE0D9563CBD7B507F69              | 1970-01-01 00:00:00 |
| LAYOUT_1E16DA4A5F48DC29802FFA4757E0DB5A4              | 1970-01-01 00:00:00 |
| LAYOUT_44C21CCF67CA6C9842782D4E1F33F672C              | 1970-01-01 00:00:00 |
```
_and so on for 5000+ lines_

**After 1st cache:flush**
```
+-------------------------------------------+---------------------+
| TRANSLATE_DE_DE_FRONTEND_1_ULTIMO_DEFAULT | 1970-01-01 00:00:00 |
| DB_PDO_MYSQL_DDL_log_visitor_info_1       | 2016-02-24 10:05:49 |
| CONFIG_GLOBAL                             | 1970-01-01 00:00:00 |
| CONFIG_GLOBAL_ADMIN                       | 1970-01-01 00:00:00 |
| CONFIG_GLOBAL_ADMINHTML                   | 1970-01-01 00:00:00 |
| LAYOUT_1DA6BE985AF26054AD20AEC1685E25621  | 1970-01-01 00:00:00 |
| config_theme                              | 1970-01-01 00:00:00 |
| CONFIG_GLOBAL_INSTALL                     | 1970-01-01 00:00:00 |
| STORE_REMOVED_DE_CONFIG_CACHE          | 2016-02-24 10:05:47 |
| STORE_REMOVED_NL_CONFIG_CACHE          | 2016-02-24 10:05:47 |
| CONFIG_GLOBAL_WEBSITES                    | 1970-01-01 00:00:00 |
| LAYOUT_FRONTEND_STORE1_ULTIMO_DEFAULT     | 1970-01-01 00:00:00 |
| CONFIG_GLOBAL_STORES_REMOVED_AT        | 1970-01-01 00:00:00 |
| CONFIG_GLOBAL_STORES_REMOVED_BE        | 1970-01-01 00:00:00 |
| APP_4E4ABDD8DC00C3DACB3C1597944A3B6C      | 2016-02-24 10:05:47 |
| CONFIG_GLOBAL_STORES_ADMIN                | 1970-01-01 00:00:00 |
| CONFIG_GLOBAL_STORES_DEFAULT              | 1970-01-01 00:00:00 |
| CONFIG_GLOBAL_STORES                      | 1970-01-01 00:00:00 |
| APP_E4D52B98688947405EDE639E947EE03D      | 2016-02-24 10:05:47 |
| APP_B1FB6E8F13287C01E5C05063633DDA4C      | 2016-02-24 10:05:47 |
| STORE_REMOVED_AT_CONFIG_CACHE          | 2016-02-24 10:05:47 |
| STORE_REMOVED_BE_CONFIG_CACHE          | 2016-02-24 10:05:47 |
| CONFIG_GLOBAL_STORES_REMOVED_NL        | 1970-01-01 00:00:00 |
| STORE_ADMIN_CONFIG_CACHE                  | 2016-02-24 10:05:47 |
| CORE_CACHE_OPTIONS                        | 1970-01-01 00:00:00 |
| CONFIG_GLOBAL_CRONTAB                     | 1970-01-01 00:00:00 |
| CONFIG_GLOBAL_STORES_REMOVED_DE        | 1970-01-01 00:00:00 |
| DB_PDO_MYSQL_DDL_catalog_product_entity_1 | 2016-02-24 10:05:49 |
+-------------------------------------------+---------------------+
```
**After 2nd cache:flush**
```
+--------------------------------------+---------------------+
| CONFIG_GLOBAL_WEBSITES               | 1970-01-01 00:00:00 |
| CONFIG_GLOBAL_STORES_REMOVED_BE   | 1970-01-01 00:00:00 |
| CONFIG_GLOBAL_STORES_REMOVED_AT   | 1970-01-01 00:00:00 |
| APP_4E4ABDD8DC00C3DACB3C1597944A3B6C | 2016-02-24 10:06:05 |
| CONFIG_GLOBAL_STORES_ADMIN           | 1970-01-01 00:00:00 |
| CONFIG_GLOBAL_STORES                 | 1970-01-01 00:00:00 |
| CONFIG_GLOBAL_STORES_DEFAULT         | 1970-01-01 00:00:00 |
| APP_E4D52B98688947405EDE639E947EE03D | 2016-02-24 10:06:05 |
| APP_B1FB6E8F13287C01E5C05063633DDA4C | 2016-02-24 10:06:05 |
| STORE_REMOVED_AT_CONFIG_CACHE     | 2016-02-24 10:06:05 |
| CONFIG_GLOBAL                        | 1970-01-01 00:00:00 |
| STORE_REMOVED_BE_CONFIG_CACHE     | 2016-02-24 10:06:05 |
| CONFIG_GLOBAL_STORES_MOOIEKUNST_NL   | 1970-01-01 00:00:00 |
| CONFIG_GLOBAL_ADMIN                  | 1970-01-01 00:00:00 |
| STORE_ADMIN_CONFIG_CACHE             | 2016-02-24 10:06:05 |
| CONFIG_GLOBAL_ADMINHTML              | 1970-01-01 00:00:00 |
| CONFIG_GLOBAL_CRONTAB                | 1970-01-01 00:00:00 |
| CORE_CACHE_OPTIONS                   | 1970-01-01 00:00:00 |
| STORE_REMOVED_DE_CONFIG_CACHE     | 2016-02-24 10:06:05 |
| CONFIG_GLOBAL_INSTALL                | 1970-01-01 00:00:00 |
| STORE_REMOVED_NL_CONFIG_CACHE     | 2016-02-24 10:06:05 |
| CONFIG_GLOBAL_STORES_REMOVED_DE   | 1970-01-01 00:00:00 |
+--------------------------------------+---------------------+
```

**Comment by pschoenmakers** [comment] 2016-02-24 08:41
Ok my bad.. I just noticed the same behaviour when clearing my cache in the admin. I thought this always worked as expected. But I believe my problem isn't related to magerun not clearing the cache but it's a Lesti FPC issue.

**Comment by tkn98** [comment] 2016-02-24 09:04
@pschoenmakers: If you have contact to someone from Lesti FPC perhaps we can put him into the loop and get some feedback. I don't know that module, does it interface with Redis exclusively?

**Comment by hostep** [comment] 2016-02-24 09:10
Lesti FPC is not exclusively for Redis, we use it with file based caching, and it also doesn't work using `cache:flush`, see related issue: https://github.com/netz98/n98-magerun/issues/613#issuecomment-129430953

**Comment by ktomk** [comment] 2016-02-24 20:26
@hostep: Can you check if `cache:dir:flush` helps in that scenario?

**Comment by ktomk** [comment] 2016-04-14 11:50
No furhter feedback / traction, closing for now until more feedback is available.

**Closed by ktomk** 2016-04-14 11:50 UTC

**Comment by sprankhub** [comment] 2016-08-02 07:04
I also have this issue using Redis and Lesti_Fpc. The cache is not fully flushed by the `cache:flush` command. I opened a [Lesti_Fpc issue](https://github.com/GordonLesti/Lesti_Fpc/issues/250) now and hope that we come up with a solution together.
If you need any more input, please let me know.

**Comment by Mic2005** [comment] 2016-08-03 11:14
@hans2103 is this the same issue that we see in our production enviroment? You must use the command 2, 3 times to flush the cache 100% via magerun?
