### ISSUE TITLE
script exits without completing

### ISSUE THREAD

**Issue by zainengineer** [netz98/n98-magerun#897] opened 2017-03-01 00:08 UTC
script exits without completing.
For example a simple script `sample.magerun`
```
sys:setup:run
cache:list
```

`n98-magerun script sample.magerun` will never display cache list
it is a side effect of fix done in #854

**Comment by ktomk** [comment] 2017-03-01 06:15
Looks like a duplicate of #895.

**Comment by zainengineer** [comment] 2017-03-01 06:16
yes it is duplicate.

**Comment by ktomk** [comment] 2017-03-01 06:18
I can also confirm it fixed in the develop version:

	$ echo "sys:setup:run
	> cache:list" | bin/n98-magerun script
	done
	+-------------+----------+
	| code        | status   |
	+-------------+----------+
	| config      | enabled  |
	| layout      | disabled |
	| block_html  | disabled |
	| translate   | disabled |
	| collections | disabled |
	| eav         | enabled  |
	| config_api  | disabled |
	| config_api2 | disabled |
	+-------------+----------+

**Comment by zainengineer** [comment] 2017-03-01 06:20
It would be great if in future some unit test can catch the issue.

like checkout the output of a complex long script

**Comment by tkn98** [comment] 2017-03-01 11:49
another thing would be support of the verbose option to show the command before executing it. That done, these errors are easier to catch in the future *and* users can more easily debug their scripts if they need to.

**Comment by zainengineer** [comment] 2017-05-09 02:49
It is still not fixed.
Should be fixed by https://github.com/netz98/n98-magerun/issues/895 
is it because changes are not released yet ? 
https://github.com/netz98/n98-magerun/commit/83c828f97a4b2b5b50e102a1f1681a87907532bb

**Comment by ktomk** [comment] 2017-05-09 06:55
That commit is in *develop* only, so it is not yet part of the *,master* release.

**Comment by zainengineer** [comment] 2017-05-09 06:56
thanks @ktomk 

Any timeline on when it will be fixed in production release?

**Closed by ktomk** 2017-05-09 06:55 UTC

**Comment by cmuench** [comment] 2017-08-26 08:14
Release is planned for Monday 26. August.
