### ISSUE TITLE
Not showing db:dump

### ISSUE THREAD

**Issue by rafaelstz** [netz98/n98-magerun#717] opened 2015-10-28 13:45 UTC
**Not showing db:dump**

![screen](https://cloud.githubusercontent.com/assets/610598/10790234/4c2f10ce-7d69-11e5-9724-8c125f74bcec.png)

**Comment by tkn98** [comment] 2015-10-28 15:01
Which magerun version are you using? Do you have some tweaked config or similar? I tried myself with various versions but was unable to reproduce.

db:dump appears normally between drop and import (just a-z order).

**Comment by AydinHassan** [comment] 2015-10-28 16:21
Probably related to [this](https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Database/DumpCommand.php#L71). Is `exec` disabled on your machine or are you on Windows?

**Comment by rafaelstz** [comment] 2015-10-28 17:33
I saw now, that only happens in the ssh server. The Magerun is clean, without modification, running in version **1.97.5** in Ubuntu 04.14 LTS. Location is normal.

![test](https://cloud.githubusercontent.com/assets/610598/10797317/3d1aedea-7d89-11e5-81ca-3931a812256b.png)

**Comment by ktomk** [comment] 2015-10-28 18:40
that's interesting. perhaps PHP function `exec()` is disabled on that server in CLI?

**Comment by rafaelstz** [comment] 2015-10-28 19:50
yes @ktomk :sweat_smile:

**Comment by tkn98** [comment] 2015-10-29 08:58
That's the reason then. You can have the `db:dump` command on non-windows OSes when the `exec()` PHP function is available in CLI (which normally makes sense, perhaps the CLI variant is using the ini of the web SAPI on that host?).

I close the issue for now. Feel free to provide any additional feedback and also to reopen it if it's not yet resolved for you.

**Closed by tkn98** 2015-10-29 08:58 UTC

**Comment by bery** [comment] 2016-01-03 23:00
Would be nice to have this documented in the command reference list to ease the search why its missing on Win powered machine though..

**Comment by ktomk** [comment] 2016-01-04 00:06
@bery: The list command does not show disabled commands. On verbose mode one could create a message which module is disabled (but no reason would be given). Magento ist not supported on Windows btw., so we normally do not take care for Magrun about windows unless a developer is willing to handle it properly. So if you're interested, PR's are welcome :)

**Comment by bery** [comment] 2016-01-08 11:20
More than showing it on the command line, one liner in the db:dump docs, saying "does not work on Win" would be nice :)

**Comment by tkn98** [comment] 2016-01-08 12:22
@bery: Magerun is not expected to work on windows at all. The commands who do work regardless you execute them of windows is what already is nice :) - That saying: If you patch the command to work on windows, we probably accept those patches.

**Comment by bery** [comment] 2016-01-21 15:23
Most of the commands I have tried so far work on Windows as well.. in my setup :)

**Comment by johnhughes1984** [comment] 2016-02-08 11:40
+1 for some kind of message to explain why certain functions are disabled, or documentation on what their prerequisites/dependencies are and lost a good bit of time tracking it down :)

I was getting the below response:

`[InvalidArgumentException]`
`Command "db:dump" is not defined.`

Thanks to this thread it turned out to be `exec()` being disabled on our Ubuntu servers (our hosting solution disables `exec()` by default for CLI and FPM)

**Comment by ktomk** [comment] 2016-02-08 20:06
@johnhughes1984: That's because commands that are not enabled count technically as undefined in the Symfony2 console framework we use. At that place in time, you can not even send messages to the output :/.

I now enabled the command *always* and if something is missing, the command will throw exceptions telling which function is missing or if it's on the wrong operating system.

This is now part of the development version which you can `self-update` to by using the `--unstable` switch. It will become part of the next stable version.
