### ISSUE TITLE
Magerun issue with MySQL 8.0.21

### ISSUE THREAD

**Issue by nniecws** [netz98/n98-magerun#1116] opened 2020-10-05 07:56 UTC
There is an issue if you are running magerun on **MySQL 8.0.21**:

If you are trying to run a cron by **sys:cron:run** you get this error:

SQLSTATE[HY000]: General error: 1525 Incorrect TIMESTAMP value: '', query was: SELECT `main_table`.* FROM `cron_schedule` AS `main_table` WHERE (`status` = 'pending') AND (`job_code` = 'sitemap_generate') AND (`scheduled_at` =   
  '')
General error: 1525 Incorrect TIMESTAMP value: ''

On MySQL 8.0.21 empty string comparisons like **`scheduled_at` =   ''** are not allowed and throw an exception.

**Comment by cmuench** [comment] 2020-10-05 09:06
Duplicate of #1115

**Closed by cmuench** 2020-10-05 09:06 UTC
Labels: bug

**Comment by nniecws** [comment] 2020-10-14 15:41
@cmuench Thank you very much for your work. I downloaded the developer version of magerun and it works perfectly now!
