### ISSUE TITLE
Cannot install via standard `composer require` command ?

### ISSUE THREAD

**Issue by xxorax** [netz98/n98-magerun#803] opened 2016-03-31 11:50 UTC
When I try to install magerun with standard composer command :
```
# composer require n98/magerun
Using version ^1.97 for n98/magerun
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - n98/magerun 1.97.9 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.8 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.7 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.6 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.5 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.4 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.3 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.2 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.16 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.15 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.12 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.11 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.10 requires composer/composer dev-master#9f6fdfd703f433bd0777fd89fb4684908a6c4f06 -> no matching package found.
    - n98/magerun 1.97.1 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.0 requires composer/composer 1.0.*@dev -> no matching package found.
    - Installation request for n98/magerun ^1.97 -> satisfiable by n98/magerun[1.97.0, 1.97.1, 1.97.10, 1.97.11, 1.97.12, 1.97.15, 1.97.16, 1.97.2, 1.97.3, 1.97.4, 1.97.5, 1.97.6, 1.97.7, 1.97.8, 1.97.9].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```
The goal is to use `composer global require n98/magerun`, then it does not need to move the bin or do other manipulations by hand/non-standard.
Even I set "minimum-stability": "dev" in the composer.json, I still get similar negative result.

**Comment by tkn98** [comment] 2016-03-31 13:19
You can use magerun only as a root package. So you can't require it. Please follow the standard installation instructions to install it. 

Duplicate of: #746

**Closed by tkn98** 2016-03-31 13:19 UTC

**Comment by ktomk** [comment] 2016-04-04 00:08
@xxorax: Were you able to find a non-composer command to install Magerun easily on your system globally? That would be good to know otherwise it's perhaps useful we provide more fluid set-up options with Magerun.

**Comment by ktomk** [comment] 2016-04-10 09:58
@xxorax:Next stable Magerun will have reqs on stable composer. This should allow you to install it globally without require-dev. Ref: b8241ceaf3b646fe2906d335409cc95915f22581

**Comment by ktomk** [comment] 2016-04-11 08:12
@xxorax: I can confirm this working now for

    $ composer require n98/magerun
