### ISSUE TITLE
PHP 7.3 Warning message

### ISSUE THREAD

**Issue by arosenhagen** [netz98/n98-magerun#1014] opened 2019-03-25 10:22 UTC
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in phar:///usr/local/bin/n98-magerun/src/N98/Magento/Command/ScriptCommand.php on line 136

**Comment by cmuench** [comment] 2019-03-25 11:02
@arosenhagen Magento 1 is not compatible with PHP 7.3. We will never add PHP 7.3 support to n98-magerun1. Is your M1 shop running with PHP 7.3?

**Comment by arosenhagen** [comment] 2019-03-26 08:30
I'm currently testing M1 on PHP 7.3. Have you any reports why it wouldn't be compatible (now that 7.2 support is official)? At first glance I don't see huge issues...

**Comment by ktomk** [comment] 2019-03-26 18:24
That's a code smell anyway, so the warning is worth to followed after normally. Regardless which PHP version, it's only that PHP 7.3 warns.

**Comment by cmuench** [comment] 2019-03-26 21:36
@ktomk it not about the code smell. We can fix that in this case. It is more the topic "should we support Mage to versions which are not officially supported".
Next question... What if official Magento support ends next year. How should we handle new PHP versions? How long should we maintain n98-magerun?

**Comment by ktomk** [comment] 2019-03-27 10:07
> "should we support Mage to versions which are not officially supported".

I would say so, yes. Unless there are actual criteria for such a decision.

> "What if official Magento support ends next year. How should we handle new PHP versions"

Depends on the support period and how Magento progresses (e.g. Open Mage etc.). For the PHP versions I think it's useful to be forward compatible.

> "How long should we maintain n98-magerun?"

As long as it is in use, especially when the "we" is the community. Individually this may vary, but I think it's worth to make ones mind how maintenance does look like and how to keep the level of service/quality.

**Comment by arosenhagen** [comment] 2019-03-27 10:19
a usual case is: we use `n98-magerun modman:generate > modman` to easily generate the proper modman file. Since the warning is echoed, the file ends up with the warning message above the actual content. I know it's just a cosmetic issue... ;-)

**Comment by ktomk** [comment] 2019-03-27 13:45
Why is the warning echoed? If it's from PHP it should go into STDERR not STDOUT, which seems not to be as you report. I can't reproduce this right now, but this looks a bit fishy. Maybe I once enabled display errors? o_O let me check.

**Comment by cmuench** [comment] 2019-07-07 10:48
@arosenhagen The development version is now patched.
You can test it with "n98-magerun.phar self-update --unstable".

**Comment by cmuench** [comment] 2019-07-19 18:07
Fix is released with v1.103.1.

**Closed by cmuench** 2019-07-19 18:07 UTC
Labels: bug
