### ISSUE TITLE
OpenMage 20.4.0 / PHP 8.2.19 compatibility

### ISSUE THREAD

**Issue by aminemekkidph2m** [netz98/n98-magerun#1424] opened 2024-06-04 16:10 UTC
## Describe the bug

It looks like current version is not compatible with PHP 8.2 version. 

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun/vendor/symfony/yaml/Inline.php on line 49

## Expected behaviour

Output not returning errors.

## Steps to reproduce the issue

Running any command using PHP>8.2 version. 
I'm currently using OpenMage version of Magento.

## Technical details

- Host Machine OS : Windows using WSL.

**Comment by cmuench** [comment] 2024-06-04 16:20
@aminemekkidph2m The actual stable version of n98-magerun does not support PHP 8.2.
It's not compatible.
Compatibility is still in progress. The next planned version is v3.0.0. The currently development version is related to the PR #1326 
A version tested with PHP 8.1 is in the develop branch. You can try it by updating with `n98-magerun.phar self-update --unstable`.
I cannot guarantee that this will work for you. I personally do not work actively on the n98-magerun1 version.
Sadly there is not much progress here.

**Comment by sreichel** [comment] 2024-06-05 19:39
@aminemekkidph2m please test unreleased v3.0 and let us know if the error is still there. I'll fix it in time.

(The linked PR is the "next step" that removes some outdated code.)

**Comment by sreichel** [comment] 2024-06-05 19:41
@cmuench can you please check why the build failed for v3?

**Comment by cmuench** [comment] 2024-06-05 19:58
> @cmuench can you please check why the build failed for v3?

@sreichel Looks like the self-update test job is failing. I found the same error in the issues of the Guzzle project. Maybe we need to upgrade the http client library.

**Comment by sreichel** [comment] 2024-06-06 02:40
Tested some commands with v3 and php8.2 ... no errors.

**Comment by cmuench** [comment] 2024-06-06 14:00
@sreichel i was able to reproduce the issue in my ddev environment. I will try to fix it.

**Comment by cmuench** [comment] 2024-06-06 14:35
@sreichel A rebuild of the phar file fixed the download test job.

**Comment by cmuench** [comment] 2024-06-06 14:58
@sreichel I added OpenMage 20.1.0 and 20.9.0 to the Github Actions.
Currently the installation with the install command fails due to a missing Zend_Cache class.
Is there something special in the installation process in OpenMage >20.0?

**Comment by sreichel** [comment] 2024-06-06 19:04
@cmuench i will test it later. Sounds similar to https://github.com/OpenMage/magento-lts/issues/2961

Edit: in 20.1.0 lib/Zend was replaced with composer dependency.

**Comment by cmuench** [comment] 2024-06-07 09:30
@sreichel it's strange. We install via composer. It seems that the dependency is loaded correctly.

**Comment by sreichel** [comment] 2024-06-07 19:45
@cmuench yeah, actions log seems okay. Local ddev works too.

Is it possible that vendor is outside of installDir "magento"?

Possible related: https://github.com/OpenMage/magento-lts/pull/3226

I have no other idea so far and try to debug with https://nektosact.com

**Comment by sreichel** [comment] 2024-06-08 03:33
@cmuench seems to work with this change:

```

      - name: Install OpenMage
        run: |
          mkdir magento
          cd magento
          php ../bin/n98-magerun --no-interaction install \
```

**Comment by sreichel** [comment] 2024-06-08 03:47
@cmuench seems to work too:

```
      - name: Install OpenMage
        run: |
          php bin/n98-magerun --no-interaction install \
           ....
        env:
          COMPOSER_VENDOR_PATH : vendor
```

**Comment by cmuench** [comment] 2024-06-08 08:45
@sreichel I just allowed the Github Actions jobs running phpunit and bats to fail by setting `continue-on-error: true`.
In the CI/CD result it's now always OK but we can check the result log then.
And at least the installation can be tested for this versions until the issues is fixed in OpenMage.

**Comment by sreichel** [comment] 2024-06-08 12:36
@cmuench provided a first fix over there.

Note: maybe we have to add some lines to clean EAV-cache. But lets wait with this.

**Comment by sreichel** [comment] 2024-07-13 12:40
@aminemekkidph2m can we close it?

**Comment by sreichel** [comment] 2024-08-22 12:20
Closed for no response. v3-dev works with php8.x.

**Closed as completed by sreichel** 2024-08-22 12:20 UTC
Labels: bug
