### ISSUE TITLE
db:dump - sed: RE error: illegal byte sequence - mysqldump: Got errno 32 on write

### ISSUE THREAD

**Issue by convenient** [netz98/n98-magerun#771] opened 2016-02-12 10:42 UTC
#### Error
When running the `magerun db:dump` command I received the following error.

```
sed: RE error: illegal byte sequence
mysqldump: Got errno 32 on write
```

#### Explanation
I traced it back to the cool definer logic introduced in #130 

It turned out to be related to the `$LANG` variable. My OSX machine had `$LANG` defined like:

```
echo $LANG
en_GB.UTF-8
```

#### Workaround

We got the dump command to work by running it like
```
export LANG=C
magerun db:dump
```

Thanks @dank00 for the workaround.

**Comment by cmuench** [comment] 2016-02-15 13:14
I confirm this behavior on OSX.
If we prepend `LANG=C LC_CTYPE=C LC_ALL=C` before `sed` the problem is gone away.

**Comment by dank00** [comment] 2016-02-15 14:23
Hi @cmuench busy at work at the moment but I've put this here #773

**Comment by ktomk** [comment] 2016-02-15 20:57
This is now part of the development version and will be part of the next stable release. Please update to the unstable version and try again. It should now run w/o the error. Please provide feedback if you can, I'll close for now as I'm confident that it works.

**Closed by ktomk** 2016-02-15 20:57 UTC

**Comment by convenient** [comment] 2016-02-15 21:22
Bam! If only all issues could be resolved this quickly / easily.
