### ISSUE TITLE
Running 'sys:setup:run' in n98-magerun script prematurely ends execution of script file.

### ISSUE THREAD

**Issue by nocturnalfrog** [netz98/n98-magerun#895] opened 2017-02-22 17:08 UTC
This is probably caused by the fix for issue: #854

Content of n98-magerun script:
```
cache:flush  

# Command below gets executed and displays 'done'
sys:setup:run

# The following line no longer gets executed
config:set "web/cookie/cookie_domain" example.com
```

**Comment by ktomk** [comment] 2017-02-22 17:39
Thank you for the report, the cause you spotted, do you have something more specific in mind what is causing this? is it that we `exit()` from PHP already?

**Comment by nocturnalfrog** [comment] 2017-02-22 18:01
I think removing line `  $this->getApplication()->setAutoExit(false);` causes the \Symfony\Component\Console\Application to fall back to the default value for $autoExit (`private $autoExit = true;`) which seems to cause an actual exit when the command is run instead of returning the exit code: \Symfony\Component\Console\Application:150

My guess is that this then actually exits the `n98-magerun script myscriptfile.magerun` as well.

**Comment by ktomk** [comment] 2017-02-22 19:01
I could reproduce the issue and have applied a fix to the development version. From a quick scan on the code there are potentially other commands that are similarly incompatible with the `script` command. If that is the case the same kind of fix should be possible. Just saying if you run (or did run) over a similar behaviour for other Magerun commands in scripts.

We believe that the bug reported is fixed in the stable version. It can be upgraded to it using the `self-update` command.

**Closed by ktomk** 2017-02-22 19:01 UTC
Labels: bug
