### ISSUE TITLE
There are no commands defined in the "customer" namespace.

### ISSUE THREAD

**Issue by MrRoyce** [netz98/n98-magerun#741] opened 2015-12-29 02:18 UTC
I installed, updated and tested magerun, and I can run some of the commands such as 'sys:check', etc.  But when I try to get customers with 'customer:list', I get the error message 

Invalid Argument Extension,  There are no commands defined in the "customer" namespace.

Any idea how to resolve this?

**Comment by ktomk** [comment] 2015-12-30 00:11
That sounds like as-if there would be no customer:* command at all. When you call the list command, is it shown in the list of all commands?

**Comment by MrRoyce** [comment] 2015-12-30 04:26
Nope, no customer commands at all on the server.  The commands go from config to db.

It works fine on my localhost.  Both are using 1.97.7

**Comment by ktomk** [comment] 2015-12-30 09:38
I tried with 1.97.7 and 1.97.8. Please run the selfupdate command to upgrade to the current version first. I'm not sure if that solves your problem but it's best if you're checking against the latest version. If there is any reason you can't upgrade, just let me know as well.

**Comment by MrRoyce** [comment] 2015-12-30 22:21
I ran the selfupdate which says its updating to 1.97.8, but the version command still shows 1.97.7

**Comment by ktomk** [comment] 2015-12-31 00:44
@MrRoyce: I just verified what you comment and can confirm there is a problem with the download of the latest version. But nevertheless, this should not trigger your original issue, so let's for the moment ignore it (created #742).

In [your previous comment](https://github.com/netz98/n98-magerun/issues/741#issuecomment-167933987) you wrote that 

> Nope, no customer commands at all on the server (with PHP 5.3.24 - shared hosting). 

That is a clear sign that on your system the PHP function [`exec`](http://php.net/exec) is not available. Unless that *exec* function  is available no customer commands are enabled.

I hope this clarifies your issue.

Can you share which hoster you're using and can you confirm that the exec function is disabled on that shared hosting?

**Comment by MrRoyce** [comment] 2015-12-31 01:37
You are correct, exec is not available on the server.  I'd rather not mention the hosting company. I inherited this project that had been hastily switched to them by the prior developer.  I had a long discussion with them on Twitter and email with their Community Developer about why they would default to PHP 5.3. for shared hosting but I guess something like 'exec' being disabled is reasonable. 

Thankfully this is just a temp server that can be scrapped.  Everything works fine on my local, 

BTW I searched a bit, but didn't see any info on exec being a requirement for Magento?  Or is it Magerun that needs it?  Is that and any other system requirements documented anywhere?

I'll close this ticket.  Thanks for your help.

**Comment by ktomk** [comment] 2015-12-31 08:04
Hi @MrRoyce, `exec` in this case is a requirement by the Magerun customer commands. I only quickly checked but *this should not be the case* as those commands as far as I could see only do use the Magento API.

For Magento, I think there is a requirement for `exec` and/or `shell_exec` because the core component `cron.php` is making use of it (Magento 1). Having these functions disabled in a shared hosting environment is often a sign that the (rights) configuration is not done well. On that temporary hoster you've got another smell is the PHP version you mention. If you wouldn't consider alternatives yet, this would be what I would personally suggest you right away :).

I re-open as I think it's a flaw that the customer commands are looking for exec. Let me know if you can help with reviewing those commands (if you like).

**Comment by cmuench** [comment] 2015-12-31 08:33
@ktomk Yes, the version was not up to date on files.magerun.net. I started the build manually and got some warnings with the new reproduceable timestamp libraries but the file was correcly generated and deployed. Let's investigate this if you are back in the office.

**Comment by ktomk** [comment] 2015-12-31 11:09
Hi @cmuench, okay let's review that next week.

@MrRoyce: I'm now preparing a fix for the issue you reported here as it uncovered a flaw we had in the code due to changes in 5555a782d2d52e6dd01ae9b7bedd05fe468f1e64 - so you don't need to take a look at all.

**Comment by ktomk** [comment] 2015-12-31 14:44
@MrRoyce: The missing customer commands have been fixed in the development version of Magerun (ref e2df81b075e7cf3d12e53a741fb699b65049b821). You can upgrade to the unstable version to get it:

    php -f n98-magerun.phar -- self-update --unstable

After updating, the customer commands are available even if `exec()` is disabled on the host. This should solve your reported issue regardless of the temporary sorry hosting.

I'll close for now as I think it's done, just leave feedback how it worked for you.

**Closed by ktomk** 2015-12-31 14:44 UTC
Labels: bug

**Comment by MrRoyce** [comment] 2015-12-31 16:24
Yes, it works!  Finally!  Thanks for your perseverance, and hopefully this will help someone else down the road.

All the best to you and your family in 2016.  I am done for the year!

**Comment by ktomk** [comment] 2015-12-31 16:29
Thanks for your greetings and wishes. And not only this is a fix for you, but your report also unconvered a much bigger underlying flaw that is now fixed. This should make N98-Magerun even more stable!
