### ISSUE TITLE
Unable to uninstall n98-magerun

### ISSUE THREAD

**Issue by arisdario** [netz98/n98-magerun#734] opened 2015-11-23 16:27 UTC
Im trying to uninstall n98-magerun because i can't disable the log 'n98-magerun-events.log' it is running over 2 days and the isze of file is about 2GB, is there a way to remove/uninstall n98-magerun to stop creating this annoying log files?

**Comment by ktomk** [comment] 2015-11-23 17:16
Your report is a bit unspecific. Generally magerun can be uninstalled by removing it form memory (either RAM while it is running but also from the file-system by deleting the phar file). Your operating system manual should contain at least two commands to do these things: 1.) killing proceses, 2.) deleting files.

Further I've got the following questions:

- What is the exact command-line that is running for over two days? Or is just that log growing?
- What is written into that log-file? Can you provide an excerpt?

**Comment by hostep** [comment] 2015-11-23 18:27
I think @arisdario is talking about the `dev:events:listen` command which is added by the [magerun-addons](https://github.com/peterjaap/magerun-addons#listen-for-all-magento-events-on-the-fly) project

@arisdario: if you run this [patch](https://github.com/peterjaap/magerun-addons/blob/3468d5a31f842f6cca954df5a9ee70b8b5e270e6/src/Elgentos/Magento/Command/Dev/Events/0001-Revert-Added-logging-of-events.patch) or just manually remove that line, it will be fixed

**Comment by arisdario** [comment] 2015-11-23 18:42
exactly, i installed that module to check the issues with SUPEE 6788, but it generates a lot of event logs that i don't need. n98-magerun is nice to have but if you see files growing in the server is not good, also in the documentation is not specified how to kill it or uninstall.

**Comment by hostep** [comment] 2015-11-23 20:44
@arisdario: you are mistaking the magerun-addons project with this one, which is the n98-magerun tool. The magerun-addons project is an addon to the n98-magerun tool. It provides extra features. One of them is to enable logging of all events Magento dispatches. You probably ran that command, somehow it got killed and left that extra logging line in the file `app/Mage.php` and now it keeps logging those events.

To fix this, open the file `app/Mage.php`, look for the `dispatchEvent` function, and remove the line `Mage::log($name, null, 'n98-magerun-events.log');`
This will fix your issue.

This problem isn't caused by the n98-magerun tool, it's caused by the addon, where something went wrong. So you don't need to uninstall n98-magerun to fix it. Just remove that one line from the `app/Mage.php` file and everything will be fine again :)

Pinging @peterjaap, so he is aware this can happen.

@ktomk or @arisdario: please close this issue, it is not relevant to this project :)

**Comment by ktomk** [comment] 2015-11-24 01:46
Okay, as far as I understand so far, uninstalling n98-magerun won't help at this point. So I close it for the moment.

@hostep: If there is anything in magerun core that can help to support with the addon issue, please let me know.

**Closed by ktomk** 2015-11-24 01:46 UTC

**Comment by peterjaap** [comment] 2015-11-24 07:50
I'm guessing you've come across this error when running ```dev:events:listen```; https://github.com/peterjaap/magerun-addons/issues/21

The issue is in Dutch so I'll help a bit; the command listens for CTRL-C to see when you're done with reading the log. It then triggers the removal of the log line in app/Mage.php. Your server probably didn't have this command so the clean-up action wasn't triggered. I'll add a notice to do this manually when the function isn't defined.

**Comment by peterjaap** [comment] 2015-11-24 07:57
I've added a notice; https://github.com/peterjaap/magerun-addons/commit/04601d988e70416fffe33ce740e13aa045e540c9

**Comment by arisdario** [comment] 2015-11-24 09:55
@peterjaap i deleted the addon, i rebooted the server, the log is still generating, please let me know how to complete remove this addon, is not fair that you create some extensions that we cannot delete after finding an issue. Thanks

**Comment by arisdario** [comment] 2015-11-24 09:58
Also is not funny to find that you Modify the Mage.php file and is causing some serious problems like: `Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 130968 bytes) in /home/data/magento/app/Mage.php on line 447`

**Comment by peterjaap** [comment] 2015-11-24 10:33
As stated before at least two times in this thread, remove the Mage::log call from app/Mage.php. Or do a ```git checkout app/Mage.php``` if you're working with Git (which I sincerely hope you do).

**Comment by peterjaap** [comment] 2015-11-24 10:35
And to top it all off; you shouldn't run development commands in production mode.

**Comment by tkn98** [comment] 2015-11-24 11:09
@arisdario: Please do not comment here as this is not related to magerun itself. Also everybody here is not only offering direct help but is also pretty transparent about what is going on and I can't see how this is unfair of any kind. I do understand it is an unpleasant situation for you, but please keep a civil tone here and expect good faith from everybody taking part.

And as @peterjaap commented: You need to remove that line from Mage.php / reset that file. The system you've exectued that add-on command on was not capable of it which is why you see this issue. This was not intended at all.
