### ISSUE TITLE
Latest version 1.97.30 suppresses indexing error messages

### ISSUE THREAD

**Issue by danemacmillan** [netz98/n98-magerun#915] opened 2017-05-17 20:31 UTC
I've been running `1.97.7` for a while now, and finally decided to upgrade to `1.97.30` in anticipation of issue #911 being resolved.

In doing so, I noticed that n98 does not actually display any errors when it fails. I don't know when this started happening, but both of these issues combined make for a frustrating situation. What that means is that while #911 will likely respond with the correct non-zero exit code, it won't actually contain any error information that can be used to further debug a problem.

When n98 version `1.97.30` fails:

<img width="874" alt="screen shot 2017-05-17 at 4 25 47 pm" src="https://cloud.githubusercontent.com/assets/4390491/26174657/20002e74-3b1e-11e7-9a52-aac7f11fcee9.png">

Note the lack of error information. There should be more information that displays before the date is displayed on the next line.

When n98 version `1.97.7` fails:

<img width="840" alt="screen shot 2017-05-17 at 4 24 08 pm" src="https://cloud.githubusercontent.com/assets/4390491/26174678/29a1a2be-3b1e-11e7-91e5-7360743467fc.png">

Note that the `date` command is run in a chain `&&`, which should not display when an error occurs (#911), but the latest version *also* does not provide the error at all.

These command are each run like this, with the same options passed:

```
./n98-magerun.phar -vvv index:reindex catalog_product_flat
```

The latest version dumps more information, like "Add command," but does not provide error messages. Is there a fourth verbosity option now `-vvvv`? How do I get errors back?

**Comment by ktomk** [comment] 2017-05-17 21:33
`-vvv` is the highest verbosity level.

It looks like this is a regression, but reading the other issue Christian didn't meant to say there is a new stable version available. He suggested to upgrade to the unstable version

~~~
 n98-magerun.phar self-update --unstable
                                 ^^^^^^
~~~

If you want to try, that should have the commit.

However not showing the error in 1.97.30 looks not good either. But perhaps it is fixed in develop as well.

My suggestion would be to give the unstable version a try and report back if it solved the two issues (a) exit status b) error message) or not.

**Comment by cmuench** [comment] 2019-06-29 07:39
Should be fixed.

**Closed by cmuench** 2019-06-29 07:39 UTC
Labels: bug
